// Generated by https://quicktype.io

export interface Geoapi {
    candidates: Candidate[];
    status:     string;
}

export interface Candidate {
    formatted_address: string;
    geometry:          Geometry;
    name:              string;
}

export interface Geometry {
    location: Location;
    viewport: Viewport;
}

export interface Location {
    lat: number;
    lng: number;
}

export interface Viewport {
    northeast: Location;
    southwest: Location;
}
